# Generated by Django 3.2.25 on 2025-03-19 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='userdetails',
        ),
    ]
